In [1]:
import tensorflow as tf
import os
import numpy as np
import scipy as sp
from tqdm import tqdm_notebook
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from inspect import signature
from PIL import Image
from scipy.cluster.vq import kmeans
import matplotlib.pyplot as plt
from multiprocessing import Pool
from tensorflow.keras import optimizers
from tensorflow.keras import metrics
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.callbacks import ReduceLROnPlateau
from decimal import *
from numpy import dot
from numpy.linalg import norm



# folder where all *.npy files are located
path_to_data = r'C:\Users\Lenovo\Downloads\Sem_3\RP\Labelling_softmax\files'

# create log files in `current dir/`
logs = 'logs/' 

reference_features = np.load(os.path.join(path_to_data, 'training_features_62_classes.npy'))
reference_features = reference_features / np.linalg.norm(reference_features, 2, axis=1, keepdims=True)
reference_classes = np.load(os.path.join(path_to_data, 'training_classids_62_classes.npy'))
reference_probs = np.load(os.path.join(path_to_data, 'training_probabilities_62_classes.npy'))

incremental_features = np.load(os.path.join(path_to_data, 'validation_features_62_classes.npy'))

incremental_features = incremental_features / np.linalg.norm(incremental_features, 2 , axis=1, keepdims=True)
incremental_classes = np.load(os.path.join(path_to_data, 'validation_classids_62_classes.npy'))
incremental_probs = np.load(os.path.join(path_to_data, 'validation_probabilities_62_classes.npy'))

test_features = np.load(os.path.join(path_to_data, 'test_features_62_classes.npy'))
test_features = test_features / np.linalg.norm(test_features, 2 , axis=1, keepdims=True)
test_classes = np.load(os.path.join(path_to_data, 'test_classids_62_classes.npy'))
test_probs = np.load(os.path.join(path_to_data, 'test_probabilities_62_classes.npy'))

class_mapping = np.load(os.path.join(path_to_data, 'class_mapping_62_classes.npy'), allow_pickle=True).item()
unique_classes = np.unique(reference_classes)

test_dataset = tf.data.Dataset.from_tensor_slices((test_features, tf.keras.utils.to_categorical(test_classes)))
test_dataset = test_dataset.batch(32)


In [14]:
print(reference_features.shape)
print(incremental_features.shape)
print(test_features.shape)
print(reference_features.max())

(40603, 2048)
(17401, 2048)
(31000, 2048)
0.88654864


In [80]:

def eucl_distance(x,features):
    diff = x - features          
    dist = np.sqrt(np.square(diff).sum(axis=-1))
    return dist

def soft_distance(x, features, gamma):
    diff = x - features          
    dist = np.sqrt(np.square(diff).sum(axis=-1))
    return np.exp(-gamma * dist).sum()

def calculate_distances(features, anchor, gamma):
    labels = np.zeros((features.shape[0],))
    probs = np.zeros_like(labels)
    for i, feature in enumerate(features): 
        distances = np.zeros((len(unique_classes),))
        for cid in unique_classes:            
            n = soft_distance(feature, anchor[cid], gamma)            
            ds = np.finfo(float).eps
            for ccid in unique_classes:                
                d = soft_distance(feature, anchor[ccid], gamma)
                ds += d
            
            distances[cid] = n/ds
            
        labels[i] = distances.argmax()
        probs[i]  = distances.max()
    return labels, probs

def get_soft_voting(features, anchor, gamma):       
    labels = []
    probs = []
    cpus = os.cpu_count() - 2 # keep two cpus please
    num_chunks = features.shape[0] // (cpus - 1)
    
    with Pool(processes=cpus) as pool:
        results = []

        for chunk in range(cpus):
            start = chunk * num_chunks
            
            if chunk == cpus - 1:
                sub_features = features[start:]
            else:
                sub_features = features[start:start + num_chunks]
            
            results.append(pool.apply_async(calculate_distances, args=(sub_features, anchor, gamma)))
        
        with tqdm_notebook(total=features.shape[0]) as pbar:        
            for result in results:
                label, prob = result.get()
                labels.extend(label)
                probs.extend(prob)
                pbar.update(len(label))
        
    return labels, probs

def get_anchor_points(num_points):
    anchor_points = []
    for cid in tqdm_notebook(unique_classes, desc='calculate anchor points'):
        indices = np.where(reference_classes == cid)[0]
        class_features = reference_features[indices]
        codebook, _ = kmeans(class_features, num_points, iter=200)
        #codebook /= np.linalg.norm(codebook, 2, axis=1, keepdims=True)
        
        anchor_points += [codebook]
    return np.array(anchor_points)

def calculate_weights(features, name):
    if name == 'baseline':
        return np.ones(features.shape[0])
    if name == 'weighted_prob':
        weight_prob = np.zeros_like(probs)
        weight_prob = np.float(1.0) - (probs.max(axis=1))
        return np.array(weight_prob)
    if name == 'active_0.1':
        prob_test=(1.0-np.array(probs.max(axis=1)))
        prob_test_new = []
        index = []
        for i in range(len(prob_test)):
            if prob_test[i] >= 0.1:
                prob_test_new.append((prob_test[i]))
                index.append(i)
        return np.array(prob_test_new), np.array(index)
    if name == 'active_0.3':
        prob_test=(1.0-np.array(probs.max(axis=1)))
        prob_test_new = []
        index = []
        for i in range(len(prob_test)):
            if prob_test[i] >= 0.3:
                prob_test_new.append((prob_test[i]))
                index.append(i)
        return np.array(prob_test_new), np.array(index)
    if name == 'active_0.5':
        prob_test=(1.0-np.array(probs.max(axis=1)))
        prob_test_new = []
        index = []
        for i in range(len(prob_test)):
            if prob_test[i] >= 0.5:
                prob_test_new.append((prob_test[i]))
                index.append(i)
        return np.array(prob_test_new), np.array(index)
    if name == 'active_0.7':
        prob_test=(1.0-np.array(probs.max(axis=1)))
        prob_test_new = []
        index = []
        for i in range(len(prob_test)):
            if prob_test[i] >= 0.7:
                prob_test_new.append((prob_test[i]))
                index.append(i)
        return np.array(prob_test_new), np.array(index)
    if name == 'active_0.9':
        prob_test=(1.0-np.array(probs.max(axis=1)))
        prob_test_new = []
        index = []
        for i in range(len(prob_test)):
            if prob_test[i] >= 0.9:
                prob_test_new.append((prob_test[i]))
                index.append(i)
        return np.array(prob_test_new), np.array(index)

In [3]:
anchors = np.load('anchor_points.npy')

In [4]:
labels_soft = np.load('labels_l2.npy')
probs = np.load('prob_l2.npy')

In [41]:
np.save('labels_gamma10',labels_l2)
np.save('probs_gamma10',prob_l2)

In [111]:
labels_soft=incremental_probs.argmax(-1)
probs=incremental_probs
print(np.array(probs).max())

1.0


In [75]:
t = []
for i in range(len(incremental_features)):
    t_1 = []
    for j in range(62):
        t_2 = []
        for k in range(10):
            y= cosine_dist(incremental_features[i],anchors[j,k,:],1.5)
            t_2+=[y]
        t_1+=[t_2]
    t+=[t_1]
print(np.array(t).shape)

(17401, 62, 10)


In [76]:
print(np.array(t))

[[[0.40700662 0.60008472 0.55102077 ... 0.4565239  0.59312296 0.69113448]
  [0.44033653 0.42703801 0.38895518 ... 0.7360574  0.78532252 0.46443748]
  [0.81436101 0.83488175 0.86050227 ... 0.81945911 0.83160858 0.82052197]
  ...
  [0.70854023 0.68446732 0.71513122 ... 0.73259747 0.66332841 0.68682861]
  [0.89529008 0.7082231  0.83129407 ... 0.82205689 0.85139193 0.80672376]
  [0.77823991 0.83042416 0.78349556 ... 0.82337011 0.78567642 0.79287495]]

 [[0.63051149 0.61036608 0.64928779 ... 0.57506666 0.61129844 0.71632928]
  [0.61151841 0.62852392 0.61809009 ... 0.80901884 0.86785939 0.6829344 ]
  [0.87880749 0.89076098 0.91807322 ... 0.82928783 0.88934181 0.87794321]
  ...
  [0.78305027 0.74316707 0.76482731 ... 0.76303206 0.75656243 0.71086645]
  [0.83221117 0.64716047 0.76614054 ... 0.79186626 0.73225778 0.7607199 ]
  [0.80873032 0.86091274 0.82931185 ... 0.84894027 0.79351149 0.81687872]]

 [[0.71531892 0.74250728 0.73242742 ... 0.60236919 0.75421934 0.04336387]
  [0.68513268 0.732793

In [37]:
dist_prob =[]
for i in range(len(incremental_features)):
    for i_anch in range(62):
        dist_class = anchors[int(i_anch),:,:]
        anch = []
        for anch_point in dist_class:
            n_d = sp.spatial.distance.cdist(np.expand_dims(incremental_features[i],0), np.expand_dims(anch_point,0), 'cosine')
            anch += [n_d]
    dist_prob += [anch]

In [38]:
print(dist_prob,np.array(dist_prob).shape)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [29]:
res_new=[]
for feat in incremental_features:
    for anch in range(62):
        x = sp.spatial.distance.cdist(incremental_features[i], anch_point, 'cosine')
        res_new += [x]

print(np.array(res_new).shape)

(1078862, 1, 10)


In [110]:
print(labels_soft = incremental_classes)

In [23]:
x_1,y_1=calculate_weights(incremental_features,'weighted_prob')
print(x_1.shape)

NameError: name 'probs' is not defined

In [7]:
print(incremental_features[0].shape)
print(anchors[0][0].shape)

(2048,)
(2048,)


In [117]:
np.array(prob_l2).max()

0.14274030570384727

In [112]:
accu = accuracy_score(incremental_classes, labels_soft )
print(accu)

0.6671455663467617


In [113]:
accu_softmax = accuracy_score(incremental_classes, incremental_probs.argmax(-1) )
print(accu_softmax)

0.6671455663467617


In [36]:
np.save('labels_l2',labels_l2)

In [17]:
anchors.shape


(62, 10, 2048)

In [18]:
labels_soft

array([ 0,  0,  0, ..., 61, 61, 61], dtype=int32)

In [89]:
np.linalg.norm(reference_features[2])

0.9999999

In [84]:
for class_anchor in anchors:
    print(np.linalg.norm(class_anchor, 2, axis = 0).)

[0.01451669 0.0122645  0.01339182 ... 0.14653212 0.01101872 0.00648832]
[0.01320241 0.02109883 0.01426366 ... 0.10881281 0.00408078 0.01051635]
[0.10007218 0.01597041 0.00659267 ... 0.01942493 0.03644577 0.01108169]
[0.03927026 0.01624916 0.11495394 ... 0.00742108 0.04862261 0.03737556]
[0.00926008 0.01142468 0.06746539 ... 0.00596215 0.02744677 0.0235248 ]
[0.02082544 0.01939648 0.02740207 ... 0.01579915 0.02335838 0.01513518]
[0.0338123  0.01029657 0.00697266 ... 0.04726903 0.00979435 0.01131043]
[0.18779463 0.0452951  0.01080569 ... 0.03966454 0.01137339 0.00897109]
[0.03809591 0.06821112 0.01449743 ... 0.02022204 0.01284392 0.02335776]
[0.0128266  0.0075739  0.02177125 ... 0.0096603  0.06007257 0.01894998]
[0.01152607 0.0266415  0.05527271 ... 0.11630904 0.01775121 0.01554709]
[0.04419288 0.0161972  0.00943661 ... 0.02089878 0.06922931 0.04984759]
[0.00848678 0.01385924 0.01591597 ... 0.00713631 0.0196746  0.01517598]
[0.01773687 0.03229105 0.07495635 ... 0.0065653  0.05520876 0.01

In [82]:

weig= calculate_weights(incremental_features,'weighted_prob')
print(weig)

[0.2870627  0.6543143  0.00142133 ... 0.07339907 0.00238127 0.00073856]


In [107]:
1-(probs[3].max())

0.2014973759651184

In [83]:

prob_test_new,ind = calculate_weights(incremental_features,'active_0.1')

In [86]:

print(prob_test_new)

[0.2870627  0.6543143  0.20149738 ... 0.492535   0.19299942 0.54772735]
[    0     1     3 ... 17386 17389 17397]


In [57]:
prob_test=(1.0-np.array(probs))
prob_test_new = []
index = []
for i in range(len(prob_test)):
    if prob_test[i] >= 0.1:
        prob_test_new.append((prob_test[i]))
        index.append(i)
        

In [114]:
labesl_soft

(17401,)

In [8]:
len(incremental_classes[index])

12

In [ ]:
experiment_weights_types = ['baseline']
for name in experiment_weights_types:
    for attempt in range(3):
        # sample weights 
        weights = calculate_weights(incremental_features, name)

        incremental_dataset = tf.data.Dataset.from_tensor_slices((incremental_features, tf.keras.utils.to_categorical(labels_soft),weights))
        incremental_dataset = incremental_dataset.shuffle(2048).batch(32)
        # load pre-trained keras model
        model = tf.keras.models.load_model(os.path.join(path_to_data, 'submodel_62_classes.hdf5'), compile=False)

        # use SGD optimizer
        optimizer = optimizers.Adam(lr=.0001)
        model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

        # define callbacks 
        callbacks = [
            ModelCheckpoint(
                os.path.join(logs, '{}_model_62_classes.hdf5'.format(name)), monitor='val_accuracy', 
                verbose=0, save_best_only=True, save_weights_only=False, mode='auto'),
            # you can use tensorboard --logdir path/to/log/dir to visualize the training parameters like loss and accuracy
            TensorBoard(os.path.join(logs, 'sm_'+name, str(attempt))),
            #ReduceLROnPlateau(monitor='val_accuracy', factor=0.1,patience=10, min_lr=0.000001, verbose=1)

        ] 

        # start training for 250 epochs
        model.fit_generator(
            incremental_dataset,
            epochs=500,
            callbacks=callbacks,
            validation_data=test_dataset)

        model.load_weights(os.path.join(logs, '{}_model_62_classes.hdf5'.format(name)))
        
        y_pred = model.predict(test_dataset)
        cm_b = confusion_matrix(test_classes, np.array(y_pred).argmax(axis=1))
        
        np.save(os.path.join('cm_sm_'+name+'_'+str(attempt)),cm_b)
        pred_accu = accuracy_score(test_classes, np.array(y_pred).argmax(axis=1) )
        print(os.path.join('cm_sm_'+name+'_'+str(attempt)),pred_accu)


Epoch 1/500
544/544 [==============================] - 5s 10ms/step - loss: 3.7941 - accuracy: 0.5188 - val_loss: 3.7441 - val_accuracy: 0.3468
Epoch 2/500
544/544 [==============================] - 5s 10ms/step - loss: 3.5826 - accuracy: 0.4196 - val_loss: 3.5797 - val_accuracy: 0.3306
Epoch 3/500
544/544 [==============================] - 5s 10ms/step - loss: 3.3947 - accuracy: 0.4279 - val_loss: 3.4234 - val_accuracy: 0.3577
Epoch 4/500
544/544 [==============================] - 5s 10ms/step - loss: 3.2201 - accuracy: 0.4712 - val_loss: 3.2737 - val_accuracy: 0.4004
Epoch 5/500
544/544 [==============================] - 5s 10ms/step - loss: 3.0562 - accuracy: 0.5220 - val_loss: 3.1304 - val_accuracy: 0.4398
Epoch 6/500
544/544 [==============================] - 5s 10ms/step - loss: 2.9014 - accuracy: 0.5713 - val_loss: 2.9933 - val_accuracy: 0.4723
Epoch 7/500
544/544 [==============================] - 5s 10ms/step - loss: 2.7555 - accuracy: 0.6096 - val_loss: 2.8624 - val_accuracy:

544/544 [==============================] - 5s 10ms/step - loss: 0.3811 - accuracy: 0.9192 - val_loss: 0.9796 - val_accuracy: 0.7078
Epoch 114/500
544/544 [==============================] - 5s 10ms/step - loss: 0.3786 - accuracy: 0.9197 - val_loss: 0.9800 - val_accuracy: 0.7077
Epoch 115/500
544/544 [==============================] - 5s 9ms/step - loss: 0.3763 - accuracy: 0.9199 - val_loss: 0.9806 - val_accuracy: 0.7077
Epoch 116/500
544/544 [==============================] - 5s 10ms/step - loss: 0.3740 - accuracy: 0.9206 - val_loss: 0.9809 - val_accuracy: 0.7077
Epoch 117/500
544/544 [==============================] - 5s 10ms/step - loss: 0.3717 - accuracy: 0.9209 - val_loss: 0.9812 - val_accuracy: 0.7075
Epoch 118/500
544/544 [==============================] - 5s 10ms/step - loss: 0.3695 - accuracy: 0.9213 - val_loss: 0.9817 - val_accuracy: 0.7074
Epoch 119/500
544/544 [==============================] - 5s 10ms/step - loss: 0.3673 - accuracy: 0.9225 - val_loss: 0.9822 - val_accuracy: 

544/544 [==============================] - 5s 10ms/step - loss: 0.2228 - accuracy: 0.9654 - val_loss: 1.0655 - val_accuracy: 0.7020
Epoch 226/500
544/544 [==============================] - 5s 10ms/step - loss: 0.2220 - accuracy: 0.9652 - val_loss: 1.0663 - val_accuracy: 0.7018
Epoch 227/500
544/544 [==============================] - 5s 10ms/step - loss: 0.2211 - accuracy: 0.9659 - val_loss: 1.0672 - val_accuracy: 0.7018
Epoch 228/500
544/544 [==============================] - 5s 10ms/step - loss: 0.2202 - accuracy: 0.9660 - val_loss: 1.0680 - val_accuracy: 0.7019
Epoch 229/500
544/544 [==============================] - 5s 10ms/step - loss: 0.2194 - accuracy: 0.9663 - val_loss: 1.0689 - val_accuracy: 0.7019
Epoch 230/500
544/544 [==============================] - 5s 10ms/step - loss: 0.2184 - accuracy: 0.9665 - val_loss: 1.0699 - val_accuracy: 0.7018
Epoch 231/500
544/544 [==============================] - 5s 10ms/step - loss: 0.2176 - accuracy: 0.9669 - val_loss: 1.0704 - val_accuracy:

544/544 [==============================] - 5s 9ms/step - loss: 0.1490 - accuracy: 0.9856 - val_loss: 1.1634 - val_accuracy: 0.6992
Epoch 338/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1485 - accuracy: 0.9857 - val_loss: 1.1642 - val_accuracy: 0.6993
Epoch 339/500
544/544 [==============================] - 5s 9ms/step - loss: 0.1480 - accuracy: 0.9858 - val_loss: 1.1649 - val_accuracy: 0.6992
Epoch 340/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1476 - accuracy: 0.9859 - val_loss: 1.1658 - val_accuracy: 0.6992
Epoch 341/500
544/544 [==============================] - 5s 9ms/step - loss: 0.1471 - accuracy: 0.9862 - val_loss: 1.1667 - val_accuracy: 0.6991
Epoch 342/500
544/544 [==============================] - 5s 9ms/step - loss: 0.1466 - accuracy: 0.9863 - val_loss: 1.1675 - val_accuracy: 0.6992
Epoch 343/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1461 - accuracy: 0.9864 - val_loss: 1.1685 - val_accuracy: 0.6

544/544 [==============================] - 5s 9ms/step - loss: 0.1048 - accuracy: 0.9943 - val_loss: 1.2573 - val_accuracy: 0.6965
Epoch 450/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1045 - accuracy: 0.9943 - val_loss: 1.2581 - val_accuracy: 0.6965
Epoch 451/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1042 - accuracy: 0.9944 - val_loss: 1.2588 - val_accuracy: 0.6965
Epoch 452/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1039 - accuracy: 0.9943 - val_loss: 1.2596 - val_accuracy: 0.6966
Epoch 453/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1035 - accuracy: 0.9944 - val_loss: 1.2604 - val_accuracy: 0.6966
Epoch 454/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1032 - accuracy: 0.9944 - val_loss: 1.2616 - val_accuracy: 0.6965
Epoch 455/500
544/544 [==============================] - 5s 10ms/step - loss: 0.1029 - accuracy: 0.9945 - val_loss: 1.2624 - val_accuracy: 

In [ ]:
np.ones(incremental_features.shape[0]).shape

In [20]:
y_pred = model.predict(test_dataset)
    
cm_b = confusion_matrix(test_classes, np.array(y_pred).argmax(axis=1))

In [21]:
print(np.array(y_pred).argmax(axis=1))

[ 0  0 26 ... 61 61  7]


In [ ]:
print(test_classes)

In [ ]:
print(cm)

In [22]:
pred_accu = accuracy_score(test_classes, np.array(y_pred).argmax(axis=1) )
print(pred_accu)

0.7978387096774193


In [23]:
np.save(os.path.join('cm_probablity_baseline_'+str(attempt)),cm_b)

In [68]:
np.save('cm_probablity_baseline_1',cm_b)

In [83]:
experiment_weights_types = ['active_0.1','active_0.3','active_0.5','active_0.7','active_0.9']
for name in experiment_weights_types:
    for attempt in range(3):
        # sample weights 
        weights,ind = calculate_weights(incremental_features, name)

        incremental_dataset = tf.data.Dataset.from_tensor_slices((incremental_features[ind], tf.keras.utils.to_categorical(incremental_classes[ind]),weights))
        incremental_dataset = incremental_dataset.shuffle(2048).batch(32)
        # load pre-trained keras model
        model = tf.keras.models.load_model(os.path.join(path_to_data, 'submodel_62_classes.hdf5'), compile=False)

        # use SGD optimizer
        optimizer = optimizers.Adam(lr=.0001)
        model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

        # define callbacks 
        callbacks = [
            ModelCheckpoint(
                os.path.join(logs, '{}_model_62_classes.hdf5'.format(name)), monitor='val_accuracy', 
                verbose=0, save_best_only=True, save_weights_only=False, mode='auto'),
            # you can use tensorboard --logdir path/to/log/dir to visualize the training parameters like loss and accuracy
            TensorBoard(os.path.join(logs,'l2_'+name,str(attempt))),
            #ReduceLROnPlateau(monitor='val_accuracy', factor=0.1,patience=10, min_lr=0.000001, verbose=1)

        ] 

        # start training for 250 epochs
        model.fit_generator(
            incremental_dataset,
            epochs=500,
            callbacks=callbacks,
            validation_data=test_dataset)

        model.load_weights(os.path.join(logs, '{}_model_62_classes.hdf5'.format(name)))
        
        y_pred = model.predict(test_dataset)
        cm_b = confusion_matrix(test_classes, np.array(y_pred).argmax(axis=1))
        
        np.save(os.path.join('cm_l2_'+name+'_'+str(attempt)),cm_b)
        pred_accu = accuracy_score(test_classes, np.array(y_pred).argmax(axis=1) )
        print(os.path.join('cm_l2_'+name+'_'+str(attempt)),pred_accu)
        
        

Epoch 1/500
538/538 [==============================] - 5s 10ms/step - loss: 2.9298 - accuracy: 0.3063 - val_loss: 3.8008 - val_accuracy: 0.5241
Epoch 2/500
538/538 [==============================] - 5s 10ms/step - loss: 2.7813 - accuracy: 0.4224 - val_loss: 3.6439 - val_accuracy: 0.6289
Epoch 3/500
538/538 [==============================] - 5s 10ms/step - loss: 2.6663 - accuracy: 0.5259 - val_loss: 3.4961 - val_accuracy: 0.6814
Epoch 4/500
538/538 [==============================] - 5s 10ms/step - loss: 2.5586 - accuracy: 0.6059 - val_loss: 3.3551 - val_accuracy: 0.7045
Epoch 5/500
538/538 [==============================] - 6s 10ms/step - loss: 2.4567 - accuracy: 0.6608 - val_loss: 3.2204 - val_accuracy: 0.7181
Epoch 6/500
538/538 [==============================] - 5s 10ms/step - loss: 2.3599 - accuracy: 0.6960 - val_loss: 3.0914 - val_accuracy: 0.7257
Epoch 7/500
538/538 [==============================] - 5s 10ms/step - loss: 2.2677 - accuracy: 0.7181 - val_loss: 2.9680 - val_accuracy:

538/538 [==============================] - 5s 9ms/step - loss: 0.4653 - accuracy: 0.8606 - val_loss: 0.6608 - val_accuracy: 0.8193
Epoch 114/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4630 - accuracy: 0.8634 - val_loss: 0.6591 - val_accuracy: 0.8195
Epoch 115/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4610 - accuracy: 0.8626 - val_loss: 0.6574 - val_accuracy: 0.8197
Epoch 116/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4589 - accuracy: 0.8633 - val_loss: 0.6558 - val_accuracy: 0.8197
Epoch 117/500
538/538 [==============================] - 6s 10ms/step - loss: 0.4569 - accuracy: 0.8627 - val_loss: 0.6542 - val_accuracy: 0.8198
Epoch 118/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4549 - accuracy: 0.8638 - val_loss: 0.6526 - val_accuracy: 0.8197
Epoch 119/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4529 - accuracy: 0.8648 - val_loss: 0.6510 - val_accuracy: 

538/538 [==============================] - 5s 10ms/step - loss: 0.3198 - accuracy: 0.8994 - val_loss: 0.5722 - val_accuracy: 0.8281
Epoch 226/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3189 - accuracy: 0.9008 - val_loss: 0.5719 - val_accuracy: 0.8282
Epoch 227/500
538/538 [==============================] - 5s 9ms/step - loss: 0.3181 - accuracy: 0.9000 - val_loss: 0.5715 - val_accuracy: 0.8282
Epoch 228/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3173 - accuracy: 0.9007 - val_loss: 0.5712 - val_accuracy: 0.8284
Epoch 229/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3164 - accuracy: 0.9002 - val_loss: 0.5708 - val_accuracy: 0.8282
Epoch 230/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3155 - accuracy: 0.9008 - val_loss: 0.5705 - val_accuracy: 0.8285
Epoch 231/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3147 - accuracy: 0.9020 - val_loss: 0.5701 - val_accuracy: 

538/538 [==============================] - 5s 10ms/step - loss: 0.2432 - accuracy: 0.9269 - val_loss: 0.5495 - val_accuracy: 0.8301
Epoch 338/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2426 - accuracy: 0.9270 - val_loss: 0.5494 - val_accuracy: 0.8301
Epoch 339/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2421 - accuracy: 0.9280 - val_loss: 0.5493 - val_accuracy: 0.8301
Epoch 340/500
538/538 [==============================] - 6s 11ms/step - loss: 0.2415 - accuracy: 0.9274 - val_loss: 0.5492 - val_accuracy: 0.8301
Epoch 341/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2410 - accuracy: 0.9284 - val_loss: 0.5491 - val_accuracy: 0.8300
Epoch 342/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2405 - accuracy: 0.9277 - val_loss: 0.5490 - val_accuracy: 0.8301
Epoch 343/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2400 - accuracy: 0.9281 - val_loss: 0.5489 - val_accuracy:

538/538 [==============================] - 5s 10ms/step - loss: 0.1911 - accuracy: 0.9470 - val_loss: 0.5431 - val_accuracy: 0.8318
Epoch 450/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1906 - accuracy: 0.9474 - val_loss: 0.5431 - val_accuracy: 0.8319
Epoch 451/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1903 - accuracy: 0.9474 - val_loss: 0.5431 - val_accuracy: 0.8321
Epoch 452/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1899 - accuracy: 0.9474 - val_loss: 0.5431 - val_accuracy: 0.8321
Epoch 453/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1895 - accuracy: 0.9475 - val_loss: 0.5430 - val_accuracy: 0.8321
Epoch 454/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1891 - accuracy: 0.9476 - val_loss: 0.5430 - val_accuracy: 0.8321
Epoch 455/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1887 - accuracy: 0.9484 - val_loss: 0.5430 - val_accuracy:

538/538 [==============================] - 5s 10ms/step - loss: 0.6538 - accuracy: 0.8341 - val_loss: 0.8469 - val_accuracy: 0.8063
Epoch 62/500
538/538 [==============================] - 5s 10ms/step - loss: 0.6474 - accuracy: 0.8354 - val_loss: 0.8396 - val_accuracy: 0.8070
Epoch 63/500
538/538 [==============================] - 5s 10ms/step - loss: 0.6411 - accuracy: 0.8354 - val_loss: 0.8328 - val_accuracy: 0.8075
Epoch 64/500
538/538 [==============================] - 5s 10ms/step - loss: 0.6352 - accuracy: 0.8354 - val_loss: 0.8261 - val_accuracy: 0.8080
Epoch 65/500
538/538 [==============================] - 5s 10ms/step - loss: 0.6292 - accuracy: 0.8373 - val_loss: 0.8197 - val_accuracy: 0.8083
Epoch 66/500
538/538 [==============================] - 5s 10ms/step - loss: 0.6235 - accuracy: 0.8373 - val_loss: 0.8135 - val_accuracy: 0.8087
Epoch 67/500
538/538 [==============================] - 5s 9ms/step - loss: 0.6180 - accuracy: 0.8380 - val_loss: 0.8076 - val_accuracy: 0.8091

538/538 [==============================] - 5s 10ms/step - loss: 0.3720 - accuracy: 0.8841 - val_loss: 0.5971 - val_accuracy: 0.8251
Epoch 174/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3707 - accuracy: 0.8842 - val_loss: 0.5964 - val_accuracy: 0.8252
Epoch 175/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3696 - accuracy: 0.8841 - val_loss: 0.5958 - val_accuracy: 0.8253
Epoch 176/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3685 - accuracy: 0.8838 - val_loss: 0.5952 - val_accuracy: 0.8253
Epoch 177/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3673 - accuracy: 0.8850 - val_loss: 0.5945 - val_accuracy: 0.8253
Epoch 178/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3662 - accuracy: 0.8851 - val_loss: 0.5939 - val_accuracy: 0.8254
Epoch 179/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3650 - accuracy: 0.8856 - val_loss: 0.5933 - val_accuracy:

538/538 [==============================] - 5s 10ms/step - loss: 0.2746 - accuracy: 0.9155 - val_loss: 0.5569 - val_accuracy: 0.8295
Epoch 286/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2740 - accuracy: 0.9156 - val_loss: 0.5567 - val_accuracy: 0.8296
Epoch 287/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2733 - accuracy: 0.9156 - val_loss: 0.5565 - val_accuracy: 0.8295
Epoch 288/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2726 - accuracy: 0.9158 - val_loss: 0.5563 - val_accuracy: 0.8295
Epoch 289/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2719 - accuracy: 0.9162 - val_loss: 0.5561 - val_accuracy: 0.8295
Epoch 290/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2713 - accuracy: 0.9166 - val_loss: 0.5560 - val_accuracy: 0.8298
Epoch 291/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2706 - accuracy: 0.9169 - val_loss: 0.5558 - val_accuracy:

538/538 [==============================] - 5s 10ms/step - loss: 0.2132 - accuracy: 0.9380 - val_loss: 0.5449 - val_accuracy: 0.8315
Epoch 398/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2126 - accuracy: 0.9382 - val_loss: 0.5448 - val_accuracy: 0.8314
Epoch 399/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2122 - accuracy: 0.9385 - val_loss: 0.5448 - val_accuracy: 0.8313
Epoch 400/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2118 - accuracy: 0.9391 - val_loss: 0.5447 - val_accuracy: 0.8315
Epoch 401/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2113 - accuracy: 0.9396 - val_loss: 0.5447 - val_accuracy: 0.8314
Epoch 402/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2109 - accuracy: 0.9388 - val_loss: 0.5446 - val_accuracy: 0.8315
Epoch 403/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2104 - accuracy: 0.9389 - val_loss: 0.5446 - val_accuracy:

538/538 [==============================] - 5s 10ms/step - loss: 2.0959 - accuracy: 0.7469 - val_loss: 2.7378 - val_accuracy: 0.7433
Epoch 10/500
538/538 [==============================] - 5s 9ms/step - loss: 2.0162 - accuracy: 0.7555 - val_loss: 2.6305 - val_accuracy: 0.7469
Epoch 11/500
538/538 [==============================] - 6s 10ms/step - loss: 1.9406 - accuracy: 0.7655 - val_loss: 2.5283 - val_accuracy: 0.7514
Epoch 12/500
538/538 [==============================] - 5s 10ms/step - loss: 1.8684 - accuracy: 0.7708 - val_loss: 2.4310 - val_accuracy: 0.7562
Epoch 13/500
538/538 [==============================] - 5s 10ms/step - loss: 1.8003 - accuracy: 0.7770 - val_loss: 2.3386 - val_accuracy: 0.7605
Epoch 14/500
538/538 [==============================] - 5s 10ms/step - loss: 1.7353 - accuracy: 0.7796 - val_loss: 2.2510 - val_accuracy: 0.7643
Epoch 15/500
538/538 [==============================] - 5s 10ms/step - loss: 1.6739 - accuracy: 0.7843 - val_loss: 2.1681 - val_accuracy: 0.7667

538/538 [==============================] - 5s 10ms/step - loss: 0.4491 - accuracy: 0.8654 - val_loss: 0.6481 - val_accuracy: 0.8203
Epoch 122/500
538/538 [==============================] - 5s 9ms/step - loss: 0.4472 - accuracy: 0.8651 - val_loss: 0.6467 - val_accuracy: 0.8202
Epoch 123/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4454 - accuracy: 0.8663 - val_loss: 0.6452 - val_accuracy: 0.8203
Epoch 124/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4435 - accuracy: 0.8671 - val_loss: 0.6438 - val_accuracy: 0.8204
Epoch 125/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4416 - accuracy: 0.8672 - val_loss: 0.6424 - val_accuracy: 0.8204
Epoch 126/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4400 - accuracy: 0.8673 - val_loss: 0.6410 - val_accuracy: 0.8205
Epoch 127/500
538/538 [==============================] - 5s 10ms/step - loss: 0.4380 - accuracy: 0.8678 - val_loss: 0.6397 - val_accuracy: 

538/538 [==============================] - 5s 10ms/step - loss: 0.3131 - accuracy: 0.9023 - val_loss: 0.5696 - val_accuracy: 0.8288
Epoch 234/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3123 - accuracy: 0.9020 - val_loss: 0.5693 - val_accuracy: 0.8287
Epoch 235/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3115 - accuracy: 0.9019 - val_loss: 0.5689 - val_accuracy: 0.8286
Epoch 236/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3106 - accuracy: 0.9027 - val_loss: 0.5686 - val_accuracy: 0.8287
Epoch 237/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3098 - accuracy: 0.9033 - val_loss: 0.5683 - val_accuracy: 0.8286
Epoch 238/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3090 - accuracy: 0.9030 - val_loss: 0.5680 - val_accuracy: 0.8287
Epoch 239/500
538/538 [==============================] - 5s 10ms/step - loss: 0.3082 - accuracy: 0.9039 - val_loss: 0.5678 - val_accuracy:

538/538 [==============================] - 5s 10ms/step - loss: 0.2389 - accuracy: 0.9288 - val_loss: 0.5487 - val_accuracy: 0.8302
Epoch 346/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2383 - accuracy: 0.9280 - val_loss: 0.5485 - val_accuracy: 0.8300
Epoch 347/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2378 - accuracy: 0.9289 - val_loss: 0.5485 - val_accuracy: 0.8301
Epoch 348/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2372 - accuracy: 0.9283 - val_loss: 0.5484 - val_accuracy: 0.8301
Epoch 349/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2367 - accuracy: 0.9291 - val_loss: 0.5482 - val_accuracy: 0.8301
Epoch 350/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2362 - accuracy: 0.9295 - val_loss: 0.5482 - val_accuracy: 0.8302
Epoch 351/500
538/538 [==============================] - 5s 10ms/step - loss: 0.2358 - accuracy: 0.9295 - val_loss: 0.5481 - val_accuracy:

538/538 [==============================] - 5s 10ms/step - loss: 0.1879 - accuracy: 0.9482 - val_loss: 0.5430 - val_accuracy: 0.8320
Epoch 458/500
538/538 [==============================] - 5s 9ms/step - loss: 0.1876 - accuracy: 0.9483 - val_loss: 0.5430 - val_accuracy: 0.8320
Epoch 459/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1871 - accuracy: 0.9484 - val_loss: 0.5429 - val_accuracy: 0.8321
Epoch 460/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1868 - accuracy: 0.9486 - val_loss: 0.5429 - val_accuracy: 0.8320
Epoch 461/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1864 - accuracy: 0.9481 - val_loss: 0.5429 - val_accuracy: 0.8319
Epoch 462/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1860 - accuracy: 0.9491 - val_loss: 0.5429 - val_accuracy: 0.8320
Epoch 463/500
538/538 [==============================] - 5s 10ms/step - loss: 0.1856 - accuracy: 0.9495 - val_loss: 0.5429 - val_accuracy: 

514/514 [==============================] - 5s 10ms/step - loss: 0.6455 - accuracy: 0.8307 - val_loss: 0.8118 - val_accuracy: 0.8088
Epoch 70/500
514/514 [==============================] - 5s 10ms/step - loss: 0.6402 - accuracy: 0.8315 - val_loss: 0.8061 - val_accuracy: 0.8091
Epoch 71/500
514/514 [==============================] - 5s 10ms/step - loss: 0.6347 - accuracy: 0.8310 - val_loss: 0.8005 - val_accuracy: 0.8096
Epoch 72/500
514/514 [==============================] - 5s 10ms/step - loss: 0.6300 - accuracy: 0.8324 - val_loss: 0.7952 - val_accuracy: 0.8099
Epoch 73/500
514/514 [==============================] - 5s 10ms/step - loss: 0.6248 - accuracy: 0.8326 - val_loss: 0.7901 - val_accuracy: 0.8102
Epoch 74/500
514/514 [==============================] - 5s 10ms/step - loss: 0.6202 - accuracy: 0.8335 - val_loss: 0.7850 - val_accuracy: 0.8105
Epoch 75/500
514/514 [==============================] - 5s 10ms/step - loss: 0.6153 - accuracy: 0.8335 - val_loss: 0.7802 - val_accuracy: 0.810

514/514 [==============================] - 5s 10ms/step - loss: 0.3843 - accuracy: 0.8806 - val_loss: 0.5959 - val_accuracy: 0.8256
Epoch 182/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3834 - accuracy: 0.8799 - val_loss: 0.5953 - val_accuracy: 0.8254
Epoch 183/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3820 - accuracy: 0.8811 - val_loss: 0.5947 - val_accuracy: 0.8254
Epoch 184/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3808 - accuracy: 0.8810 - val_loss: 0.5941 - val_accuracy: 0.8254
Epoch 185/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3795 - accuracy: 0.8820 - val_loss: 0.5935 - val_accuracy: 0.8254
Epoch 186/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3785 - accuracy: 0.8823 - val_loss: 0.5929 - val_accuracy: 0.8254
Epoch 187/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3779 - accuracy: 0.8814 - val_loss: 0.5923 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 0.2861 - accuracy: 0.9123 - val_loss: 0.5573 - val_accuracy: 0.8293
Epoch 294/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2854 - accuracy: 0.9124 - val_loss: 0.5571 - val_accuracy: 0.8294
Epoch 295/500
514/514 [==============================] - 5s 9ms/step - loss: 0.2846 - accuracy: 0.9122 - val_loss: 0.5569 - val_accuracy: 0.8293
Epoch 296/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2839 - accuracy: 0.9128 - val_loss: 0.5568 - val_accuracy: 0.8294
Epoch 297/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2834 - accuracy: 0.9135 - val_loss: 0.5566 - val_accuracy: 0.8293
Epoch 298/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2827 - accuracy: 0.9144 - val_loss: 0.5564 - val_accuracy: 0.8292
Epoch 299/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2821 - accuracy: 0.9139 - val_loss: 0.5562 - val_accuracy: 

514/514 [==============================] - 5s 10ms/step - loss: 0.2233 - accuracy: 0.9348 - val_loss: 0.5455 - val_accuracy: 0.8318
Epoch 406/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2228 - accuracy: 0.9355 - val_loss: 0.5454 - val_accuracy: 0.8318
Epoch 407/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2222 - accuracy: 0.9359 - val_loss: 0.5453 - val_accuracy: 0.8318
Epoch 408/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2216 - accuracy: 0.9358 - val_loss: 0.5453 - val_accuracy: 0.8317
Epoch 409/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2214 - accuracy: 0.9364 - val_loss: 0.5453 - val_accuracy: 0.8317
Epoch 410/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2208 - accuracy: 0.9367 - val_loss: 0.5452 - val_accuracy: 0.8317
Epoch 411/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2205 - accuracy: 0.9363 - val_loss: 0.5452 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 1.6474 - accuracy: 0.7763 - val_loss: 2.0658 - val_accuracy: 0.7656
Epoch 18/500
514/514 [==============================] - 5s 10ms/step - loss: 1.5938 - accuracy: 0.7800 - val_loss: 1.9959 - val_accuracy: 0.7674
Epoch 19/500
514/514 [==============================] - 5s 10ms/step - loss: 1.5434 - accuracy: 0.7821 - val_loss: 1.9297 - val_accuracy: 0.7700
Epoch 20/500
514/514 [==============================] - 5s 10ms/step - loss: 1.4954 - accuracy: 0.7839 - val_loss: 1.8670 - val_accuracy: 0.7724
Epoch 21/500
514/514 [==============================] - 5s 10ms/step - loss: 1.4495 - accuracy: 0.7864 - val_loss: 1.8076 - val_accuracy: 0.7739
Epoch 22/500
514/514 [==============================] - 5s 10ms/step - loss: 1.4071 - accuracy: 0.7865 - val_loss: 1.7514 - val_accuracy: 0.7760
Epoch 23/500
514/514 [==============================] - 5s 10ms/step - loss: 1.3662 - accuracy: 0.7901 - val_loss: 1.6982 - val_accuracy: 0.778

514/514 [==============================] - 5s 10ms/step - loss: 0.4603 - accuracy: 0.8615 - val_loss: 0.6432 - val_accuracy: 0.8208
Epoch 130/500
514/514 [==============================] - 5s 10ms/step - loss: 0.4585 - accuracy: 0.8621 - val_loss: 0.6419 - val_accuracy: 0.8209
Epoch 131/500
514/514 [==============================] - 5s 10ms/step - loss: 0.4565 - accuracy: 0.8623 - val_loss: 0.6406 - val_accuracy: 0.8210
Epoch 132/500
514/514 [==============================] - 5s 10ms/step - loss: 0.4547 - accuracy: 0.8630 - val_loss: 0.6393 - val_accuracy: 0.8211
Epoch 133/500
514/514 [==============================] - 5s 10ms/step - loss: 0.4529 - accuracy: 0.8645 - val_loss: 0.6380 - val_accuracy: 0.8212
Epoch 134/500
514/514 [==============================] - 5s 10ms/step - loss: 0.4511 - accuracy: 0.8641 - val_loss: 0.6368 - val_accuracy: 0.8212
Epoch 135/500
514/514 [==============================] - 5s 10ms/step - loss: 0.4494 - accuracy: 0.8642 - val_loss: 0.6356 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 0.3251 - accuracy: 0.8984 - val_loss: 0.5697 - val_accuracy: 0.8283
Epoch 242/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3245 - accuracy: 0.8999 - val_loss: 0.5694 - val_accuracy: 0.8282
Epoch 243/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3238 - accuracy: 0.8995 - val_loss: 0.5690 - val_accuracy: 0.8285
Epoch 244/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3227 - accuracy: 0.8995 - val_loss: 0.5688 - val_accuracy: 0.8285
Epoch 245/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3218 - accuracy: 0.9000 - val_loss: 0.5685 - val_accuracy: 0.8286
Epoch 246/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3212 - accuracy: 0.9012 - val_loss: 0.5682 - val_accuracy: 0.8288
Epoch 247/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3204 - accuracy: 0.9010 - val_loss: 0.5679 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 0.2496 - accuracy: 0.9262 - val_loss: 0.5492 - val_accuracy: 0.8300
Epoch 354/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2490 - accuracy: 0.9262 - val_loss: 0.5491 - val_accuracy: 0.8301
Epoch 355/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2484 - accuracy: 0.9264 - val_loss: 0.5491 - val_accuracy: 0.8302
Epoch 356/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2480 - accuracy: 0.9262 - val_loss: 0.5490 - val_accuracy: 0.8301
Epoch 357/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2474 - accuracy: 0.9263 - val_loss: 0.5489 - val_accuracy: 0.8301
Epoch 358/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2467 - accuracy: 0.9267 - val_loss: 0.5488 - val_accuracy: 0.8301
Epoch 359/500
514/514 [==============================] - 5s 11ms/step - loss: 0.2465 - accuracy: 0.9264 - val_loss: 0.5487 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 0.1972 - accuracy: 0.9457 - val_loss: 0.5435 - val_accuracy: 0.8321
Epoch 466/500
514/514 [==============================] - 5s 10ms/step - loss: 0.1969 - accuracy: 0.9460 - val_loss: 0.5435 - val_accuracy: 0.8321
Epoch 467/500
514/514 [==============================] - 5s 10ms/step - loss: 0.1965 - accuracy: 0.9463 - val_loss: 0.5434 - val_accuracy: 0.8321
Epoch 468/500
514/514 [==============================] - 5s 10ms/step - loss: 0.1959 - accuracy: 0.9467 - val_loss: 0.5434 - val_accuracy: 0.8320
Epoch 469/500
514/514 [==============================] - 5s 10ms/step - loss: 0.1955 - accuracy: 0.9467 - val_loss: 0.5434 - val_accuracy: 0.8320
Epoch 470/500
514/514 [==============================] - 5s 10ms/step - loss: 0.1953 - accuracy: 0.9466 - val_loss: 0.5434 - val_accuracy: 0.8320
Epoch 471/500
514/514 [==============================] - 5s 10ms/step - loss: 0.1947 - accuracy: 0.9469 - val_loss: 0.5434 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 0.6060 - accuracy: 0.8351 - val_loss: 0.7711 - val_accuracy: 0.8110
Epoch 78/500
514/514 [==============================] - 5s 10ms/step - loss: 0.6017 - accuracy: 0.8355 - val_loss: 0.7667 - val_accuracy: 0.8113
Epoch 79/500
514/514 [==============================] - 5s 10ms/step - loss: 0.5975 - accuracy: 0.8366 - val_loss: 0.7624 - val_accuracy: 0.8114
Epoch 80/500
514/514 [==============================] - 5s 10ms/step - loss: 0.5936 - accuracy: 0.8374 - val_loss: 0.7583 - val_accuracy: 0.8119
Epoch 81/500
514/514 [==============================] - 5s 10ms/step - loss: 0.5894 - accuracy: 0.8378 - val_loss: 0.7543 - val_accuracy: 0.8122
Epoch 82/500
514/514 [==============================] - 5s 10ms/step - loss: 0.5849 - accuracy: 0.8382 - val_loss: 0.7504 - val_accuracy: 0.8126
Epoch 83/500
514/514 [==============================] - 5s 10ms/step - loss: 0.5810 - accuracy: 0.8385 - val_loss: 0.7466 - val_accuracy: 0.812

514/514 [==============================] - 5s 10ms/step - loss: 0.3750 - accuracy: 0.8829 - val_loss: 0.5912 - val_accuracy: 0.8256
Epoch 190/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3743 - accuracy: 0.8827 - val_loss: 0.5906 - val_accuracy: 0.8256
Epoch 191/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3731 - accuracy: 0.8829 - val_loss: 0.5902 - val_accuracy: 0.8257
Epoch 192/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3720 - accuracy: 0.8845 - val_loss: 0.5896 - val_accuracy: 0.8257
Epoch 193/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3709 - accuracy: 0.8833 - val_loss: 0.5891 - val_accuracy: 0.8259
Epoch 194/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3698 - accuracy: 0.8840 - val_loss: 0.5886 - val_accuracy: 0.8260
Epoch 195/500
514/514 [==============================] - 5s 10ms/step - loss: 0.3691 - accuracy: 0.8846 - val_loss: 0.5881 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 0.2808 - accuracy: 0.9144 - val_loss: 0.5560 - val_accuracy: 0.8292
Epoch 302/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2802 - accuracy: 0.9147 - val_loss: 0.5558 - val_accuracy: 0.8293
Epoch 303/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2794 - accuracy: 0.9141 - val_loss: 0.5556 - val_accuracy: 0.8292
Epoch 304/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2787 - accuracy: 0.9142 - val_loss: 0.5555 - val_accuracy: 0.8292
Epoch 305/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2781 - accuracy: 0.9145 - val_loss: 0.5553 - val_accuracy: 0.8293
Epoch 306/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2774 - accuracy: 0.9156 - val_loss: 0.5552 - val_accuracy: 0.8293
Epoch 307/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2768 - accuracy: 0.9155 - val_loss: 0.5550 - val_accuracy:

514/514 [==============================] - 5s 10ms/step - loss: 0.2193 - accuracy: 0.9372 - val_loss: 0.5451 - val_accuracy: 0.8319
Epoch 414/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2190 - accuracy: 0.9370 - val_loss: 0.5450 - val_accuracy: 0.8319
Epoch 415/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2185 - accuracy: 0.9370 - val_loss: 0.5450 - val_accuracy: 0.8319
Epoch 416/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2180 - accuracy: 0.9382 - val_loss: 0.5450 - val_accuracy: 0.8320
Epoch 417/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2177 - accuracy: 0.9381 - val_loss: 0.5449 - val_accuracy: 0.8319
Epoch 418/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2172 - accuracy: 0.9378 - val_loss: 0.5448 - val_accuracy: 0.8319
Epoch 419/500
514/514 [==============================] - 5s 10ms/step - loss: 0.2166 - accuracy: 0.9381 - val_loss: 0.5448 - val_accuracy:

465/465 [==============================] - 5s 11ms/step - loss: 1.4601 - accuracy: 0.7669 - val_loss: 1.7349 - val_accuracy: 0.7653
Epoch 26/500
465/465 [==============================] - 5s 11ms/step - loss: 1.4231 - accuracy: 0.7687 - val_loss: 1.6887 - val_accuracy: 0.7672
Epoch 27/500
465/465 [==============================] - 5s 11ms/step - loss: 1.3882 - accuracy: 0.7705 - val_loss: 1.6447 - val_accuracy: 0.7692
Epoch 28/500
465/465 [==============================] - 5s 11ms/step - loss: 1.3544 - accuracy: 0.7718 - val_loss: 1.6028 - val_accuracy: 0.7712
Epoch 29/500
465/465 [==============================] - 5s 10ms/step - loss: 1.3235 - accuracy: 0.7755 - val_loss: 1.5629 - val_accuracy: 0.7731
Epoch 30/500
465/465 [==============================] - 5s 10ms/step - loss: 1.2933 - accuracy: 0.7783 - val_loss: 1.5250 - val_accuracy: 0.7746
Epoch 31/500
465/465 [==============================] - 5s 11ms/step - loss: 1.2652 - accuracy: 0.7773 - val_loss: 1.4889 - val_accuracy: 0.775

465/465 [==============================] - 5s 11ms/step - loss: 0.5029 - accuracy: 0.8518 - val_loss: 0.6495 - val_accuracy: 0.8205
Epoch 138/500
465/465 [==============================] - 5s 10ms/step - loss: 0.5015 - accuracy: 0.8516 - val_loss: 0.6481 - val_accuracy: 0.8206
Epoch 139/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4989 - accuracy: 0.8531 - val_loss: 0.6468 - val_accuracy: 0.8205
Epoch 140/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4967 - accuracy: 0.8534 - val_loss: 0.6455 - val_accuracy: 0.8207
Epoch 141/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4947 - accuracy: 0.8537 - val_loss: 0.6443 - val_accuracy: 0.8210
Epoch 142/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4930 - accuracy: 0.8541 - val_loss: 0.6430 - val_accuracy: 0.8209
Epoch 143/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4912 - accuracy: 0.8550 - val_loss: 0.6418 - val_accuracy:

465/465 [==============================] - 5s 10ms/step - loss: 0.3584 - accuracy: 0.8910 - val_loss: 0.5742 - val_accuracy: 0.8281
Epoch 250/500
465/465 [==============================] - 5s 11ms/step - loss: 0.3581 - accuracy: 0.8916 - val_loss: 0.5739 - val_accuracy: 0.8280
Epoch 251/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3566 - accuracy: 0.8917 - val_loss: 0.5736 - val_accuracy: 0.8280
Epoch 252/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3559 - accuracy: 0.8920 - val_loss: 0.5732 - val_accuracy: 0.8280
Epoch 253/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3549 - accuracy: 0.8916 - val_loss: 0.5730 - val_accuracy: 0.8280
Epoch 254/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3544 - accuracy: 0.8927 - val_loss: 0.5727 - val_accuracy: 0.8281
Epoch 255/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3532 - accuracy: 0.8931 - val_loss: 0.5724 - val_accuracy:

465/465 [==============================] - 5s 10ms/step - loss: 0.2766 - accuracy: 0.9203 - val_loss: 0.5523 - val_accuracy: 0.8304
Epoch 362/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2758 - accuracy: 0.9202 - val_loss: 0.5522 - val_accuracy: 0.8303
Epoch 363/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2754 - accuracy: 0.9208 - val_loss: 0.5522 - val_accuracy: 0.8303
Epoch 364/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2752 - accuracy: 0.9206 - val_loss: 0.5520 - val_accuracy: 0.8303
Epoch 365/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2744 - accuracy: 0.9209 - val_loss: 0.5519 - val_accuracy: 0.8305
Epoch 366/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2738 - accuracy: 0.9211 - val_loss: 0.5518 - val_accuracy: 0.8303
Epoch 367/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2730 - accuracy: 0.9207 - val_loss: 0.5517 - val_accuracy:

465/465 [==============================] - 5s 10ms/step - loss: 0.2196 - accuracy: 0.9413 - val_loss: 0.5454 - val_accuracy: 0.8320
Epoch 474/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2192 - accuracy: 0.9420 - val_loss: 0.5455 - val_accuracy: 0.8320
Epoch 475/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2189 - accuracy: 0.9418 - val_loss: 0.5454 - val_accuracy: 0.8320
Epoch 476/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2183 - accuracy: 0.9416 - val_loss: 0.5454 - val_accuracy: 0.8320
Epoch 477/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2179 - accuracy: 0.9416 - val_loss: 0.5454 - val_accuracy: 0.8319
Epoch 478/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2175 - accuracy: 0.9424 - val_loss: 0.5454 - val_accuracy: 0.8319
Epoch 479/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2171 - accuracy: 0.9422 - val_loss: 0.5453 - val_accuracy:

465/465 [==============================] - 5s 11ms/step - loss: 0.6506 - accuracy: 0.8242 - val_loss: 0.7731 - val_accuracy: 0.8107
Epoch 86/500
465/465 [==============================] - 5s 10ms/step - loss: 0.6458 - accuracy: 0.8250 - val_loss: 0.7690 - val_accuracy: 0.8109
Epoch 87/500
465/465 [==============================] - 5s 10ms/step - loss: 0.6420 - accuracy: 0.8269 - val_loss: 0.7650 - val_accuracy: 0.8112
Epoch 88/500
465/465 [==============================] - 5s 10ms/step - loss: 0.6382 - accuracy: 0.8271 - val_loss: 0.7611 - val_accuracy: 0.8115
Epoch 89/500
465/465 [==============================] - 5s 11ms/step - loss: 0.6338 - accuracy: 0.8283 - val_loss: 0.7573 - val_accuracy: 0.8118
Epoch 90/500
465/465 [==============================] - 5s 10ms/step - loss: 0.6298 - accuracy: 0.8265 - val_loss: 0.7536 - val_accuracy: 0.8122
Epoch 91/500
465/465 [==============================] - 5s 11ms/step - loss: 0.6263 - accuracy: 0.8282 - val_loss: 0.7500 - val_accuracy: 0.812

465/465 [==============================] - 5s 10ms/step - loss: 0.4120 - accuracy: 0.8738 - val_loss: 0.5966 - val_accuracy: 0.8252
Epoch 198/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4111 - accuracy: 0.8743 - val_loss: 0.5961 - val_accuracy: 0.8254
Epoch 199/500
465/465 [==============================] - 5s 11ms/step - loss: 0.4102 - accuracy: 0.8742 - val_loss: 0.5955 - val_accuracy: 0.8254
Epoch 200/500
465/465 [==============================] - 5s 11ms/step - loss: 0.4087 - accuracy: 0.8753 - val_loss: 0.5950 - val_accuracy: 0.8255
Epoch 201/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4076 - accuracy: 0.8747 - val_loss: 0.5944 - val_accuracy: 0.8253
Epoch 202/500
465/465 [==============================] - 5s 11ms/step - loss: 0.4064 - accuracy: 0.8752 - val_loss: 0.5939 - val_accuracy: 0.8256
Epoch 203/500
465/465 [==============================] - 5s 11ms/step - loss: 0.4055 - accuracy: 0.8756 - val_loss: 0.5934 - val_accuracy:

465/465 [==============================] - 5s 10ms/step - loss: 0.3106 - accuracy: 0.9070 - val_loss: 0.5597 - val_accuracy: 0.8296
Epoch 310/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3099 - accuracy: 0.9064 - val_loss: 0.5595 - val_accuracy: 0.8295
Epoch 311/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3094 - accuracy: 0.9073 - val_loss: 0.5593 - val_accuracy: 0.8296
Epoch 312/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3090 - accuracy: 0.9075 - val_loss: 0.5591 - val_accuracy: 0.8294
Epoch 313/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3077 - accuracy: 0.9082 - val_loss: 0.5590 - val_accuracy: 0.8295
Epoch 314/500
465/465 [==============================] - 5s 11ms/step - loss: 0.3069 - accuracy: 0.9081 - val_loss: 0.5588 - val_accuracy: 0.8294
Epoch 315/500
465/465 [==============================] - 5s 11ms/step - loss: 0.3062 - accuracy: 0.9085 - val_loss: 0.5586 - val_accuracy:

465/465 [==============================] - 5s 10ms/step - loss: 0.2438 - accuracy: 0.9321 - val_loss: 0.5475 - val_accuracy: 0.8311
Epoch 422/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2435 - accuracy: 0.9324 - val_loss: 0.5475 - val_accuracy: 0.8311
Epoch 423/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2432 - accuracy: 0.9325 - val_loss: 0.5474 - val_accuracy: 0.8313
Epoch 424/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2427 - accuracy: 0.9323 - val_loss: 0.5474 - val_accuracy: 0.8313
Epoch 425/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2417 - accuracy: 0.9332 - val_loss: 0.5473 - val_accuracy: 0.8312
Epoch 426/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2412 - accuracy: 0.9329 - val_loss: 0.5473 - val_accuracy: 0.8313
Epoch 427/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2407 - accuracy: 0.9332 - val_loss: 0.5472 - val_accuracy:

465/465 [==============================] - 5s 11ms/step - loss: 1.2102 - accuracy: 0.7815 - val_loss: 1.4215 - val_accuracy: 0.7783
Epoch 34/500
465/465 [==============================] - 5s 10ms/step - loss: 1.1855 - accuracy: 0.7841 - val_loss: 1.3904 - val_accuracy: 0.7798
Epoch 35/500
465/465 [==============================] - 5s 10ms/step - loss: 1.1611 - accuracy: 0.7847 - val_loss: 1.3608 - val_accuracy: 0.7812
Epoch 36/500
465/465 [==============================] - 5s 10ms/step - loss: 1.1385 - accuracy: 0.7863 - val_loss: 1.3326 - val_accuracy: 0.7822
Epoch 37/500
465/465 [==============================] - 5s 10ms/step - loss: 1.1172 - accuracy: 0.7873 - val_loss: 1.3059 - val_accuracy: 0.7832
Epoch 38/500
465/465 [==============================] - 5s 10ms/step - loss: 1.0966 - accuracy: 0.7881 - val_loss: 1.2802 - val_accuracy: 0.7843
Epoch 39/500
465/465 [==============================] - 5s 10ms/step - loss: 1.0761 - accuracy: 0.7898 - val_loss: 1.2558 - val_accuracy: 0.785

465/465 [==============================] - 5s 11ms/step - loss: 0.4879 - accuracy: 0.8551 - val_loss: 0.6395 - val_accuracy: 0.8211
Epoch 146/500
465/465 [==============================] - 5s 11ms/step - loss: 0.4866 - accuracy: 0.8558 - val_loss: 0.6383 - val_accuracy: 0.8213
Epoch 147/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4841 - accuracy: 0.8559 - val_loss: 0.6372 - val_accuracy: 0.8215
Epoch 148/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4825 - accuracy: 0.8578 - val_loss: 0.6361 - val_accuracy: 0.8217
Epoch 149/500
465/465 [==============================] - 5s 10ms/step - loss: 0.4808 - accuracy: 0.8582 - val_loss: 0.6350 - val_accuracy: 0.8218
Epoch 150/500
465/465 [==============================] - 5s 11ms/step - loss: 0.4789 - accuracy: 0.8582 - val_loss: 0.6339 - val_accuracy: 0.8220
Epoch 151/500
465/465 [==============================] - 5s 11ms/step - loss: 0.4771 - accuracy: 0.8586 - val_loss: 0.6328 - val_accuracy:

465/465 [==============================] - 5s 10ms/step - loss: 0.3519 - accuracy: 0.8936 - val_loss: 0.5718 - val_accuracy: 0.8281
Epoch 258/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3508 - accuracy: 0.8931 - val_loss: 0.5715 - val_accuracy: 0.8283
Epoch 259/500
465/465 [==============================] - 5s 10ms/step - loss: 0.3496 - accuracy: 0.8932 - val_loss: 0.5712 - val_accuracy: 0.8283
Epoch 260/500
465/465 [==============================] - 5s 11ms/step - loss: 0.3491 - accuracy: 0.8943 - val_loss: 0.5709 - val_accuracy: 0.8282
Epoch 261/500
465/465 [==============================] - 5s 11ms/step - loss: 0.3480 - accuracy: 0.8946 - val_loss: 0.5706 - val_accuracy: 0.8283
Epoch 262/500
465/465 [==============================] - 5s 11ms/step - loss: 0.3472 - accuracy: 0.8950 - val_loss: 0.5704 - val_accuracy: 0.8284
Epoch 263/500
465/465 [==============================] - 5s 11ms/step - loss: 0.3465 - accuracy: 0.8950 - val_loss: 0.5700 - val_accuracy:

465/465 [==============================] - 5s 11ms/step - loss: 0.2722 - accuracy: 0.9218 - val_loss: 0.5515 - val_accuracy: 0.8305
Epoch 370/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2715 - accuracy: 0.9219 - val_loss: 0.5514 - val_accuracy: 0.8305
Epoch 371/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2711 - accuracy: 0.9218 - val_loss: 0.5513 - val_accuracy: 0.8306
Epoch 372/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2702 - accuracy: 0.9217 - val_loss: 0.5512 - val_accuracy: 0.8306
Epoch 373/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2695 - accuracy: 0.9217 - val_loss: 0.5511 - val_accuracy: 0.8307
Epoch 374/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2690 - accuracy: 0.9233 - val_loss: 0.5510 - val_accuracy: 0.8305
Epoch 375/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2690 - accuracy: 0.9226 - val_loss: 0.5509 - val_accuracy:

465/465 [==============================] - 5s 10ms/step - loss: 0.2166 - accuracy: 0.9429 - val_loss: 0.5453 - val_accuracy: 0.8319
Epoch 482/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2156 - accuracy: 0.9429 - val_loss: 0.5453 - val_accuracy: 0.8318
Epoch 483/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2153 - accuracy: 0.9430 - val_loss: 0.5452 - val_accuracy: 0.8319
Epoch 484/500
465/465 [==============================] - 5s 11ms/step - loss: 0.2151 - accuracy: 0.9429 - val_loss: 0.5452 - val_accuracy: 0.8319
Epoch 485/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2143 - accuracy: 0.9432 - val_loss: 0.5452 - val_accuracy: 0.8317
Epoch 486/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2139 - accuracy: 0.9437 - val_loss: 0.5452 - val_accuracy: 0.8317
Epoch 487/500
465/465 [==============================] - 5s 10ms/step - loss: 0.2137 - accuracy: 0.9435 - val_loss: 0.5452 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.8105 - accuracy: 0.7965 - val_loss: 0.8577 - val_accuracy: 0.8047
Epoch 94/500
368/368 [==============================] - 4s 12ms/step - loss: 0.8052 - accuracy: 0.7977 - val_loss: 0.8525 - val_accuracy: 0.8050
Epoch 95/500
368/368 [==============================] - 4s 12ms/step - loss: 0.8002 - accuracy: 0.7996 - val_loss: 0.8475 - val_accuracy: 0.8053
Epoch 96/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7956 - accuracy: 0.8000 - val_loss: 0.8426 - val_accuracy: 0.8055
Epoch 97/500
368/368 [==============================] - 4s 11ms/step - loss: 0.7907 - accuracy: 0.8006 - val_loss: 0.8378 - val_accuracy: 0.8059
Epoch 98/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7848 - accuracy: 0.8021 - val_loss: 0.8332 - val_accuracy: 0.8063
Epoch 99/500
368/368 [==============================] - 4s 11ms/step - loss: 0.7825 - accuracy: 0.8023 - val_loss: 0.8286 - val_accuracy: 0.806

368/368 [==============================] - 4s 12ms/step - loss: 0.5136 - accuracy: 0.8560 - val_loss: 0.6282 - val_accuracy: 0.8225
Epoch 206/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5122 - accuracy: 0.8560 - val_loss: 0.6275 - val_accuracy: 0.8225
Epoch 207/500
368/368 [==============================] - 4s 11ms/step - loss: 0.5105 - accuracy: 0.8562 - val_loss: 0.6267 - val_accuracy: 0.8225
Epoch 208/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5085 - accuracy: 0.8571 - val_loss: 0.6260 - val_accuracy: 0.8224
Epoch 209/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5072 - accuracy: 0.8572 - val_loss: 0.6253 - val_accuracy: 0.8225
Epoch 210/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5062 - accuracy: 0.8579 - val_loss: 0.6246 - val_accuracy: 0.8224
Epoch 211/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5048 - accuracy: 0.8567 - val_loss: 0.6239 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.3867 - accuracy: 0.8940 - val_loss: 0.5792 - val_accuracy: 0.8266
Epoch 318/500
368/368 [==============================] - 4s 11ms/step - loss: 0.3857 - accuracy: 0.8942 - val_loss: 0.5789 - val_accuracy: 0.8265
Epoch 319/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3847 - accuracy: 0.8949 - val_loss: 0.5786 - val_accuracy: 0.8266
Epoch 320/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3834 - accuracy: 0.8950 - val_loss: 0.5784 - val_accuracy: 0.8267
Epoch 321/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3829 - accuracy: 0.8952 - val_loss: 0.5781 - val_accuracy: 0.8266
Epoch 322/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3821 - accuracy: 0.8945 - val_loss: 0.5779 - val_accuracy: 0.8267
Epoch 323/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3813 - accuracy: 0.8962 - val_loss: 0.5777 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.3040 - accuracy: 0.9221 - val_loss: 0.5617 - val_accuracy: 0.8281
Epoch 430/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3034 - accuracy: 0.9228 - val_loss: 0.5616 - val_accuracy: 0.8281
Epoch 431/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3021 - accuracy: 0.9229 - val_loss: 0.5615 - val_accuracy: 0.8281
Epoch 432/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3017 - accuracy: 0.9238 - val_loss: 0.5614 - val_accuracy: 0.8282
Epoch 433/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3013 - accuracy: 0.9243 - val_loss: 0.5614 - val_accuracy: 0.8282
Epoch 434/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3009 - accuracy: 0.9242 - val_loss: 0.5613 - val_accuracy: 0.8282
Epoch 435/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3000 - accuracy: 0.9244 - val_loss: 0.5613 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 1.3742 - accuracy: 0.7410 - val_loss: 1.5073 - val_accuracy: 0.7581
Epoch 42/500
368/368 [==============================] - 4s 12ms/step - loss: 1.3518 - accuracy: 0.7445 - val_loss: 1.4814 - val_accuracy: 0.7601
Epoch 43/500
368/368 [==============================] - 4s 12ms/step - loss: 1.3317 - accuracy: 0.7447 - val_loss: 1.4564 - val_accuracy: 0.7619
Epoch 44/500
368/368 [==============================] - 4s 12ms/step - loss: 1.3127 - accuracy: 0.7464 - val_loss: 1.4322 - val_accuracy: 0.7637
Epoch 45/500
368/368 [==============================] - 4s 12ms/step - loss: 1.2923 - accuracy: 0.7477 - val_loss: 1.4088 - val_accuracy: 0.7657
Epoch 46/500
368/368 [==============================] - 4s 12ms/step - loss: 1.2741 - accuracy: 0.7506 - val_loss: 1.3863 - val_accuracy: 0.7671
Epoch 47/500
368/368 [==============================] - 4s 12ms/step - loss: 1.2563 - accuracy: 0.7504 - val_loss: 1.3644 - val_accuracy: 0.769

368/368 [==============================] - 4s 12ms/step - loss: 0.6078 - accuracy: 0.8328 - val_loss: 0.6848 - val_accuracy: 0.8169
Epoch 154/500
368/368 [==============================] - 4s 11ms/step - loss: 0.6063 - accuracy: 0.8338 - val_loss: 0.6832 - val_accuracy: 0.8170
Epoch 155/500
368/368 [==============================] - 4s 12ms/step - loss: 0.6036 - accuracy: 0.8343 - val_loss: 0.6817 - val_accuracy: 0.8173
Epoch 156/500
368/368 [==============================] - 4s 12ms/step - loss: 0.6009 - accuracy: 0.8346 - val_loss: 0.6803 - val_accuracy: 0.8175
Epoch 157/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5994 - accuracy: 0.8344 - val_loss: 0.6788 - val_accuracy: 0.8178
Epoch 158/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5968 - accuracy: 0.8357 - val_loss: 0.6773 - val_accuracy: 0.8179
Epoch 159/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5945 - accuracy: 0.8366 - val_loss: 0.6759 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.4381 - accuracy: 0.8771 - val_loss: 0.5954 - val_accuracy: 0.8250
Epoch 266/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4364 - accuracy: 0.8770 - val_loss: 0.5951 - val_accuracy: 0.8250
Epoch 267/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4359 - accuracy: 0.8789 - val_loss: 0.5946 - val_accuracy: 0.8250
Epoch 268/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4339 - accuracy: 0.8779 - val_loss: 0.5942 - val_accuracy: 0.8251
Epoch 269/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4332 - accuracy: 0.8782 - val_loss: 0.5939 - val_accuracy: 0.8251
Epoch 270/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4321 - accuracy: 0.8796 - val_loss: 0.5935 - val_accuracy: 0.8253
Epoch 271/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4305 - accuracy: 0.8781 - val_loss: 0.5931 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.3385 - accuracy: 0.9103 - val_loss: 0.5677 - val_accuracy: 0.8275
Epoch 378/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3376 - accuracy: 0.9117 - val_loss: 0.5676 - val_accuracy: 0.8274
Epoch 379/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3371 - accuracy: 0.9108 - val_loss: 0.5675 - val_accuracy: 0.8274
Epoch 380/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3365 - accuracy: 0.9107 - val_loss: 0.5674 - val_accuracy: 0.8274
Epoch 381/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3356 - accuracy: 0.9107 - val_loss: 0.5672 - val_accuracy: 0.8273
Epoch 382/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3354 - accuracy: 0.9119 - val_loss: 0.5671 - val_accuracy: 0.8272
Epoch 383/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3342 - accuracy: 0.9128 - val_loss: 0.5669 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.2693 - accuracy: 0.9349 - val_loss: 0.5576 - val_accuracy: 0.8287
Epoch 490/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2687 - accuracy: 0.9353 - val_loss: 0.5575 - val_accuracy: 0.8287
Epoch 491/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2680 - accuracy: 0.9353 - val_loss: 0.5575 - val_accuracy: 0.8286
Epoch 492/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2683 - accuracy: 0.9349 - val_loss: 0.5575 - val_accuracy: 0.8287
Epoch 493/500
368/368 [==============================] - 4s 11ms/step - loss: 0.2670 - accuracy: 0.9353 - val_loss: 0.5574 - val_accuracy: 0.8287
Epoch 494/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2664 - accuracy: 0.9358 - val_loss: 0.5574 - val_accuracy: 0.8287
Epoch 495/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2660 - accuracy: 0.9361 - val_loss: 0.5573 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.7713 - accuracy: 0.8032 - val_loss: 0.8197 - val_accuracy: 0.8069
Epoch 102/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7672 - accuracy: 0.8041 - val_loss: 0.8155 - val_accuracy: 0.8073
Epoch 103/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7625 - accuracy: 0.8047 - val_loss: 0.8114 - val_accuracy: 0.8075
Epoch 104/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7580 - accuracy: 0.8056 - val_loss: 0.8073 - val_accuracy: 0.8078
Epoch 105/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7535 - accuracy: 0.8058 - val_loss: 0.8034 - val_accuracy: 0.8082
Epoch 106/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7508 - accuracy: 0.8075 - val_loss: 0.7996 - val_accuracy: 0.8086
Epoch 107/500
368/368 [==============================] - 4s 12ms/step - loss: 0.7458 - accuracy: 0.8066 - val_loss: 0.7958 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.5013 - accuracy: 0.8588 - val_loss: 0.6226 - val_accuracy: 0.8227
Epoch 214/500
368/368 [==============================] - 4s 12ms/step - loss: 0.5002 - accuracy: 0.8591 - val_loss: 0.6219 - val_accuracy: 0.8227
Epoch 215/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4987 - accuracy: 0.8592 - val_loss: 0.6212 - val_accuracy: 0.8228
Epoch 216/500
368/368 [==============================] - 5s 12ms/step - loss: 0.4976 - accuracy: 0.8593 - val_loss: 0.6205 - val_accuracy: 0.8229
Epoch 217/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4960 - accuracy: 0.8605 - val_loss: 0.6199 - val_accuracy: 0.8231
Epoch 218/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4951 - accuracy: 0.8611 - val_loss: 0.6192 - val_accuracy: 0.8231
Epoch 219/500
368/368 [==============================] - 4s 12ms/step - loss: 0.4931 - accuracy: 0.8604 - val_loss: 0.6186 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.3799 - accuracy: 0.8961 - val_loss: 0.5773 - val_accuracy: 0.8266
Epoch 326/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3790 - accuracy: 0.8961 - val_loss: 0.5770 - val_accuracy: 0.8265
Epoch 327/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3776 - accuracy: 0.8965 - val_loss: 0.5768 - val_accuracy: 0.8266
Epoch 328/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3766 - accuracy: 0.8973 - val_loss: 0.5766 - val_accuracy: 0.8266
Epoch 329/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3764 - accuracy: 0.8963 - val_loss: 0.5764 - val_accuracy: 0.8266
Epoch 330/500
368/368 [==============================] - 4s 12ms/step - loss: 0.3755 - accuracy: 0.8968 - val_loss: 0.5762 - val_accuracy: 0.8265
Epoch 331/500
368/368 [==============================] - 5s 12ms/step - loss: 0.3742 - accuracy: 0.8973 - val_loss: 0.5760 - val_accuracy:

368/368 [==============================] - 4s 12ms/step - loss: 0.2990 - accuracy: 0.9246 - val_loss: 0.5610 - val_accuracy: 0.8284
Epoch 438/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2981 - accuracy: 0.9251 - val_loss: 0.5609 - val_accuracy: 0.8285
Epoch 439/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2977 - accuracy: 0.9254 - val_loss: 0.5608 - val_accuracy: 0.8283
Epoch 440/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2973 - accuracy: 0.9253 - val_loss: 0.5608 - val_accuracy: 0.8285
Epoch 441/500
368/368 [==============================] - 5s 12ms/step - loss: 0.2962 - accuracy: 0.9251 - val_loss: 0.5607 - val_accuracy: 0.8286
Epoch 442/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2957 - accuracy: 0.9260 - val_loss: 0.5606 - val_accuracy: 0.8285
Epoch 443/500
368/368 [==============================] - 4s 12ms/step - loss: 0.2952 - accuracy: 0.9259 - val_loss: 0.5605 - val_accuracy:

129/129 [==============================] - 3s 24ms/step - loss: 2.5586 - accuracy: 0.4472 - val_loss: 2.7816 - val_accuracy: 0.4158
Epoch 50/500
129/129 [==============================] - 3s 24ms/step - loss: 2.5427 - accuracy: 0.4484 - val_loss: 2.7629 - val_accuracy: 0.4200
Epoch 51/500
129/129 [==============================] - 3s 24ms/step - loss: 2.5269 - accuracy: 0.4535 - val_loss: 2.7444 - val_accuracy: 0.4245
Epoch 52/500
129/129 [==============================] - 3s 24ms/step - loss: 2.5113 - accuracy: 0.4600 - val_loss: 2.7259 - val_accuracy: 0.4300
Epoch 53/500
129/129 [==============================] - 3s 23ms/step - loss: 2.4957 - accuracy: 0.4622 - val_loss: 2.7079 - val_accuracy: 0.4345
Epoch 54/500
129/129 [==============================] - 3s 23ms/step - loss: 2.4805 - accuracy: 0.4658 - val_loss: 2.6896 - val_accuracy: 0.4395
Epoch 55/500
129/129 [==============================] - 3s 23ms/step - loss: 2.4654 - accuracy: 0.4685 - val_loss: 2.6720 - val_accuracy: 0.443

129/129 [==============================] - 3s 24ms/step - loss: 1.4639 - accuracy: 0.7059 - val_loss: 1.5116 - val_accuracy: 0.6797
Epoch 162/500
129/129 [==============================] - 3s 23ms/step - loss: 1.4581 - accuracy: 0.7049 - val_loss: 1.5053 - val_accuracy: 0.6807
Epoch 163/500
129/129 [==============================] - 3s 23ms/step - loss: 1.4525 - accuracy: 0.7066 - val_loss: 1.4992 - val_accuracy: 0.6817
Epoch 164/500
129/129 [==============================] - 3s 23ms/step - loss: 1.4467 - accuracy: 0.7091 - val_loss: 1.4931 - val_accuracy: 0.6824
Epoch 165/500
129/129 [==============================] - 3s 23ms/step - loss: 1.4411 - accuracy: 0.7108 - val_loss: 1.4872 - val_accuracy: 0.6837
Epoch 166/500
129/129 [==============================] - 3s 23ms/step - loss: 1.4355 - accuracy: 0.7105 - val_loss: 1.4813 - val_accuracy: 0.6844
Epoch 167/500
129/129 [==============================] - 3s 23ms/step - loss: 1.4300 - accuracy: 0.7129 - val_loss: 1.4751 - val_accuracy:

129/129 [==============================] - 3s 24ms/step - loss: 1.0084 - accuracy: 0.7984 - val_loss: 1.0791 - val_accuracy: 0.7371
Epoch 274/500
129/129 [==============================] - 3s 24ms/step - loss: 1.0055 - accuracy: 0.7992 - val_loss: 1.0769 - val_accuracy: 0.7373
Epoch 275/500
129/129 [==============================] - 3s 23ms/step - loss: 1.0027 - accuracy: 0.7999 - val_loss: 1.0745 - val_accuracy: 0.7379
Epoch 276/500
129/129 [==============================] - 3s 24ms/step - loss: 0.9999 - accuracy: 0.7999 - val_loss: 1.0724 - val_accuracy: 0.7377
Epoch 277/500
129/129 [==============================] - 3s 23ms/step - loss: 0.9970 - accuracy: 0.8004 - val_loss: 1.0702 - val_accuracy: 0.7382
Epoch 278/500
129/129 [==============================] - 3s 23ms/step - loss: 0.9942 - accuracy: 0.8011 - val_loss: 1.0678 - val_accuracy: 0.7386
Epoch 279/500
129/129 [==============================] - 3s 24ms/step - loss: 0.9914 - accuracy: 0.8014 - val_loss: 1.0657 - val_accuracy:

129/129 [==============================] - 3s 23ms/step - loss: 0.7541 - accuracy: 0.8573 - val_loss: 0.9067 - val_accuracy: 0.7579
Epoch 386/500
129/129 [==============================] - 3s 23ms/step - loss: 0.7523 - accuracy: 0.8593 - val_loss: 0.9058 - val_accuracy: 0.7580
Epoch 387/500
129/129 [==============================] - 3s 23ms/step - loss: 0.7505 - accuracy: 0.8588 - val_loss: 0.9047 - val_accuracy: 0.7580
Epoch 388/500
129/129 [==============================] - 3s 23ms/step - loss: 0.7488 - accuracy: 0.8588 - val_loss: 0.9038 - val_accuracy: 0.7581
Epoch 389/500
129/129 [==============================] - 3s 23ms/step - loss: 0.7469 - accuracy: 0.8597 - val_loss: 0.9028 - val_accuracy: 0.7582
Epoch 390/500
129/129 [==============================] - 3s 23ms/step - loss: 0.7451 - accuracy: 0.8605 - val_loss: 0.9018 - val_accuracy: 0.7581
Epoch 391/500
129/129 [==============================] - 3s 24ms/step - loss: 0.7433 - accuracy: 0.8607 - val_loss: 0.9008 - val_accuracy:

129/129 [==============================] - 3s 23ms/step - loss: 0.5846 - accuracy: 0.9033 - val_loss: 0.8268 - val_accuracy: 0.7654
Epoch 498/500
129/129 [==============================] - 3s 24ms/step - loss: 0.5833 - accuracy: 0.9046 - val_loss: 0.8262 - val_accuracy: 0.7656
Epoch 499/500
129/129 [==============================] - 3s 24ms/step - loss: 0.5820 - accuracy: 0.9033 - val_loss: 0.8256 - val_accuracy: 0.7655
Epoch 500/500
129/129 [==============================] - 3s 24ms/step - loss: 0.5807 - accuracy: 0.9041 - val_loss: 0.8251 - val_accuracy: 0.7655
0.7655806451612903
Epoch 1/500
129/129 [==============================] - 3s 23ms/step - loss: 3.6973 - accuracy: 0.3089 - val_loss: 3.8784 - val_accuracy: 0.6034
Epoch 2/500
129/129 [==============================] - 3s 24ms/step - loss: 3.6439 - accuracy: 0.3091 - val_loss: 3.8466 - val_accuracy: 0.4917
Epoch 3/500
129/129 [==============================] - 3s 24ms/step - loss: 3.5980 - accuracy: 0.2737 - val_loss: 3.8171 - 

129/129 [==============================] - 3s 24ms/step - loss: 1.8376 - accuracy: 0.6204 - val_loss: 1.9307 - val_accuracy: 0.6040
Epoch 110/500
129/129 [==============================] - 3s 25ms/step - loss: 1.8287 - accuracy: 0.6221 - val_loss: 1.9203 - val_accuracy: 0.6059
Epoch 111/500
129/129 [==============================] - 3s 23ms/step - loss: 1.8199 - accuracy: 0.6233 - val_loss: 1.9103 - val_accuracy: 0.6081
Epoch 112/500
129/129 [==============================] - 3s 24ms/step - loss: 1.8113 - accuracy: 0.6248 - val_loss: 1.9000 - val_accuracy: 0.6104
Epoch 113/500
129/129 [==============================] - 3s 23ms/step - loss: 1.8026 - accuracy: 0.6269 - val_loss: 1.8900 - val_accuracy: 0.6122
Epoch 114/500
129/129 [==============================] - 3s 23ms/step - loss: 1.7941 - accuracy: 0.6294 - val_loss: 1.8803 - val_accuracy: 0.6136
Epoch 115/500
129/129 [==============================] - 3s 23ms/step - loss: 1.7856 - accuracy: 0.6315 - val_loss: 1.8707 - val_accuracy:

129/129 [==============================] - 3s 23ms/step - loss: 1.1815 - accuracy: 0.7655 - val_loss: 1.2280 - val_accuracy: 0.7198
Epoch 222/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1777 - accuracy: 0.7655 - val_loss: 1.2244 - val_accuracy: 0.7202
Epoch 223/500
129/129 [==============================] - 3s 24ms/step - loss: 1.1739 - accuracy: 0.7667 - val_loss: 1.2210 - val_accuracy: 0.7205
Epoch 224/500
129/129 [==============================] - 3s 24ms/step - loss: 1.1701 - accuracy: 0.7667 - val_loss: 1.2176 - val_accuracy: 0.7209
Epoch 225/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1663 - accuracy: 0.7679 - val_loss: 1.2142 - val_accuracy: 0.7214
Epoch 226/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1626 - accuracy: 0.7684 - val_loss: 1.2107 - val_accuracy: 0.7217
Epoch 227/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1589 - accuracy: 0.7682 - val_loss: 1.2073 - val_accuracy:

129/129 [==============================] - 3s 23ms/step - loss: 0.8576 - accuracy: 0.8353 - val_loss: 0.9696 - val_accuracy: 0.7506
Epoch 334/500
129/129 [==============================] - 3s 24ms/step - loss: 0.8555 - accuracy: 0.8367 - val_loss: 0.9681 - val_accuracy: 0.7509
Epoch 335/500
129/129 [==============================] - 3s 23ms/step - loss: 0.8533 - accuracy: 0.8370 - val_loss: 0.9668 - val_accuracy: 0.7510
Epoch 336/500
129/129 [==============================] - 3s 24ms/step - loss: 0.8511 - accuracy: 0.8387 - val_loss: 0.9652 - val_accuracy: 0.7511
Epoch 337/500
129/129 [==============================] - 3s 24ms/step - loss: 0.8490 - accuracy: 0.8389 - val_loss: 0.9638 - val_accuracy: 0.7514
Epoch 338/500
129/129 [==============================] - 3s 23ms/step - loss: 0.8468 - accuracy: 0.8377 - val_loss: 0.9623 - val_accuracy: 0.7515
Epoch 339/500
129/129 [==============================] - 3s 23ms/step - loss: 0.8446 - accuracy: 0.8399 - val_loss: 0.9610 - val_accuracy:

129/129 [==============================] - 3s 23ms/step - loss: 0.6562 - accuracy: 0.8832 - val_loss: 0.8570 - val_accuracy: 0.7625
Epoch 446/500
129/129 [==============================] - 3s 24ms/step - loss: 0.6547 - accuracy: 0.8828 - val_loss: 0.8563 - val_accuracy: 0.7626
Epoch 447/500
129/129 [==============================] - 3s 24ms/step - loss: 0.6532 - accuracy: 0.8828 - val_loss: 0.8557 - val_accuracy: 0.7627
Epoch 448/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6517 - accuracy: 0.8830 - val_loss: 0.8549 - val_accuracy: 0.7628
Epoch 449/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6503 - accuracy: 0.8840 - val_loss: 0.8542 - val_accuracy: 0.7629
Epoch 450/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6489 - accuracy: 0.8849 - val_loss: 0.8535 - val_accuracy: 0.7630
Epoch 451/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6473 - accuracy: 0.8859 - val_loss: 0.8530 - val_accuracy:

129/129 [==============================] - 3s 24ms/step - loss: 3.6974 - accuracy: 0.3125 - val_loss: 3.8784 - val_accuracy: 0.6060
Epoch 2/500
129/129 [==============================] - 3s 23ms/step - loss: 3.6440 - accuracy: 0.3147 - val_loss: 3.8466 - val_accuracy: 0.4909
Epoch 3/500
129/129 [==============================] - 3s 23ms/step - loss: 3.5982 - accuracy: 0.2875 - val_loss: 3.8170 - val_accuracy: 0.3945
Epoch 4/500
129/129 [==============================] - 3s 24ms/step - loss: 3.5563 - accuracy: 0.2641 - val_loss: 3.7891 - val_accuracy: 0.3273
Epoch 5/500
129/129 [==============================] - 3s 24ms/step - loss: 3.5178 - accuracy: 0.2493 - val_loss: 3.7623 - val_accuracy: 0.2869
Epoch 6/500
129/129 [==============================] - 3s 23ms/step - loss: 3.4820 - accuracy: 0.2384 - val_loss: 3.7363 - val_accuracy: 0.2594
Epoch 7/500
129/129 [==============================] - 3s 24ms/step - loss: 3.4484 - accuracy: 0.2379 - val_loss: 3.7110 - val_accuracy: 0.2445
Epoc

129/129 [==============================] - 3s 23ms/step - loss: 1.8018 - accuracy: 0.6267 - val_loss: 1.8890 - val_accuracy: 0.6125
Epoch 114/500
129/129 [==============================] - 3s 24ms/step - loss: 1.7932 - accuracy: 0.6303 - val_loss: 1.8793 - val_accuracy: 0.6138
Epoch 115/500
129/129 [==============================] - 3s 23ms/step - loss: 1.7848 - accuracy: 0.6298 - val_loss: 1.8696 - val_accuracy: 0.6158
Epoch 116/500
129/129 [==============================] - 3s 24ms/step - loss: 1.7764 - accuracy: 0.6337 - val_loss: 1.8600 - val_accuracy: 0.6175
Epoch 117/500
129/129 [==============================] - 3s 24ms/step - loss: 1.7681 - accuracy: 0.6361 - val_loss: 1.8507 - val_accuracy: 0.6190
Epoch 118/500
129/129 [==============================] - 3s 24ms/step - loss: 1.7598 - accuracy: 0.6378 - val_loss: 1.8411 - val_accuracy: 0.6207
Epoch 119/500
129/129 [==============================] - 3s 23ms/step - loss: 1.7517 - accuracy: 0.6383 - val_loss: 1.8316 - val_accuracy:

129/129 [==============================] - 3s 23ms/step - loss: 1.1660 - accuracy: 0.7682 - val_loss: 1.2138 - val_accuracy: 0.7214
Epoch 226/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1623 - accuracy: 0.7670 - val_loss: 1.2106 - val_accuracy: 0.7219
Epoch 227/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1585 - accuracy: 0.7679 - val_loss: 1.2069 - val_accuracy: 0.7225
Epoch 228/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1549 - accuracy: 0.7682 - val_loss: 1.2036 - val_accuracy: 0.7228
Epoch 229/500
129/129 [==============================] - 3s 23ms/step - loss: 1.1512 - accuracy: 0.7689 - val_loss: 1.2002 - val_accuracy: 0.7233
Epoch 230/500
129/129 [==============================] - 3s 24ms/step - loss: 1.1476 - accuracy: 0.7701 - val_loss: 1.1969 - val_accuracy: 0.7235
Epoch 231/500
129/129 [==============================] - 3s 24ms/step - loss: 1.1439 - accuracy: 0.7718 - val_loss: 1.1937 - val_accuracy:

129/129 [==============================] - 3s 24ms/step - loss: 0.8487 - accuracy: 0.8377 - val_loss: 0.9636 - val_accuracy: 0.7511
Epoch 338/500
129/129 [==============================] - 3s 23ms/step - loss: 0.8465 - accuracy: 0.8387 - val_loss: 0.9623 - val_accuracy: 0.7510
Epoch 339/500
129/129 [==============================] - 3s 23ms/step - loss: 0.8443 - accuracy: 0.8396 - val_loss: 0.9609 - val_accuracy: 0.7513
Epoch 340/500
129/129 [==============================] - 3s 24ms/step - loss: 0.8422 - accuracy: 0.8399 - val_loss: 0.9596 - val_accuracy: 0.7513
Epoch 341/500
129/129 [==============================] - 3s 23ms/step - loss: 0.8401 - accuracy: 0.8406 - val_loss: 0.9581 - val_accuracy: 0.7517
Epoch 342/500
129/129 [==============================] - 3s 23ms/step - loss: 0.8379 - accuracy: 0.8404 - val_loss: 0.9569 - val_accuracy: 0.7518
Epoch 343/500
129/129 [==============================] - 3s 24ms/step - loss: 0.8358 - accuracy: 0.8418 - val_loss: 0.9554 - val_accuracy:

129/129 [==============================] - 3s 24ms/step - loss: 0.6500 - accuracy: 0.8847 - val_loss: 0.8543 - val_accuracy: 0.7629
Epoch 450/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6485 - accuracy: 0.8842 - val_loss: 0.8534 - val_accuracy: 0.7630
Epoch 451/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6471 - accuracy: 0.8852 - val_loss: 0.8528 - val_accuracy: 0.7631
Epoch 452/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6456 - accuracy: 0.8857 - val_loss: 0.8521 - val_accuracy: 0.7632
Epoch 453/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6442 - accuracy: 0.8861 - val_loss: 0.8515 - val_accuracy: 0.7632
Epoch 454/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6428 - accuracy: 0.8866 - val_loss: 0.8510 - val_accuracy: 0.7631
Epoch 455/500
129/129 [==============================] - 3s 23ms/step - loss: 0.6413 - accuracy: 0.8871 - val_loss: 0.8501 - val_accuracy:

In [14]:
y_pred_x = model.predict(test_dataset)
    
cm_x = confusion_matrix(test_classes, np.array(y_pred_x).argmax(axis=1))

In [15]:
pred_accu = accuracy_score(test_classes, np.array(y_pred_x).argmax(axis=1) )
print(pred_accu)

0.8170967741935484


In [16]:
np.save('cm_probablity_ac01_1',cm_x)

In [5]:
import numpy as np
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

import matplotlib as mpl
import matplotlib.pyplot as plt

def plot_tensorflow_log(path):

    # Loading too much data is slow...
    tf_size_guidance = {
        'compressedHistograms': 10,
        'images': 0,
        'scalars': 100,
        'histograms': 1
    }

    event_acc = EventAccumulator(path, tf_size_guidance)
    event_acc.Reload()

    # Show all tags in the log file
    #print(event_acc.Tags())

    #training_accuracies =   event_acc.Scalars('training-accuracy')
    validation_accuracies = event_acc.Scalars('validation_accuracy')

    steps = 500
    x = np.arange(steps)
    y = np.zeros([steps, 2])

    for i in xrange(steps):
        #y[i, 0] = training_accuracies[i][2] # value
        y[i, 1] = validation_accuracies[i][2]

    plt.plot(x, y[:,0], label='training accuracy')
    plt.plot(x, y[:,1], label='validation accuracy')

    plt.xlabel("Steps")
    plt.ylabel("Accuracy")
    plt.title("Training Progress")
    plt.legend(loc='upper right', frameon=True)
    plt.show()


if __name__ == '__main__':
    log_file = r"C:\Users\Lenovo\Downloads\Sem_3\RP\logs\sm_baseline\0\validation\events.out.tfevents.1579560452.dst-aux-ws-11.14279.209418674.v2"
    plot_tensorflow_log(log_file)

KeyError: 'Key validation_accuracy was not found in Reservoir'

In [7]:
for event in tf.backend.summary_iterator(r"C:\Users\Lenovo\Downloads\Sem_3\RP\logs\sm_baseline\0\validation\events.out.tfevents.1579560452.dst-aux-ws-11.14279.209418674.v2"):
    for value in event.summary.value:
        print(value.tag)
        if value.HasField('simple_value'):
            print(value.simple_value)

AttributeError: module 'tensorflow' has no attribute 'backend'